<a href="https://colab.research.google.com/github/dr-mushtaq/Deep-Learning/blob/master/Deep_Learning_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#<p style="font-family:JetBrains Mono; font-weight:normal; letter-spacing: 1px; color:#207d06; font-size:100%; text-align:left;padding: 0px; border-bottom: 3px solid #207d06;">**📚Libray and Tools**</p>



1.   [torch.tensor]()-creates a 1D tensor.
2.   [marks.shape]()-shows the dimensions of the tensor.



#<p style="font-family:JetBrains Mono; font-weight:normal; letter-spacing: 1px; color:#207d06; font-size:100%; text-align:left;padding: 0px; border-bottom: 3px solid #207d06;">**📚Chapter: 1-The Fundamentals of PyTorch (Beginner)**</p>

**1D Vector in PyTorch**

In [ ]:
import torch
marks = torch.tensor([78, 85, 90, 88, 92])
print(marks)
print(marks.shape)

tensor([78, 85, 90, 88, 92])
torch.Size([5])


**2D Matrix in PyTorch**

In [ ]:
import torch
student_marks = torch.tensor([
    [78, 85, 90],
    [88, 92, 80],
    [75, 79, 95]
])
print(student_marks)
print(student_marks.shape)

tensor([[78, 85, 90],
        [88, 92, 80],
        [75, 79, 95]])
torch.Size([3, 3])


**3D Tensor Example in PyTorch**

In [ ]:
import torch
tensor_3d = torch.tensor([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])
print(tensor_3d)
print(tensor_3d.shape)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])


**Creates a tensor without initializing its values.**

Everything in pytorch is based on Tensor operations.A tensor can have different dimensions so it can be 1d, 2d, or even 3d and higher
scalar, vector, matrix, tensor



*   In PyTorch, torch.empty() creates a tensor without initializing its values.
*   List item



In [ ]:
# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(x)

tensor([1.0814e-40])


In [ ]:
x = torch.empty(3) # vector, 1D
print(x)

tensor([2.8636e-30, 0.0000e+00, 0.0000e+00])


In [ ]:
x = torch.empty(2,3) # matrix, 2D
print(x)

tensor([[1.3573e-27, 0.0000e+00, 7.5525e-12],
        [4.4060e-41, 1.4574e-43, 0.0000e+00]])


In [ ]:
x = torch.empty(2,2,3) # tensor, 3 dimensions
#x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([[[3.2314e-18, 6.0397e-07, 1.3475e+37],
         [0.0000e+00, 1.1210e-43, 0.0000e+00]],

        [[8.9683e-44, 0.0000e+00, 2.7147e-27],
         [0.0000e+00, 0.0000e+00, 1.5046e-36]]])


**other operation**

In [ ]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

tensor([[0.1431, 0.0667, 0.2929],
        [0.3570, 0.1560, 0.8778],
        [0.3742, 0.1811, 0.8992],
        [0.9674, 0.8961, 0.5235],
        [0.7803, 0.7132, 0.9680]])


In [ ]:
# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [ ]:
# check size
print(x.size())

torch.Size([5, 3])


In [ ]:
# check data type
print(x.dtype)

torch.float32


In [ ]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)


In [ ]:
# construct from data
x = torch.tensor([5.5, 3])
print(x.size())

torch.Size([2])


**Converting Dataset to PyTorch Tensors**

In [ ]:
# Import required libraries
import torch
from sklearn.datasets import load_iris

# Load the built-in Iris dataset
iris = load_iris()

# Features (flower measurements)
X = iris.data

# Labels (flower categories)
y = iris.target

# Convert NumPy arrays to PyTorch tensors
X_tensor = torch.tensor(X, dtype=torch.float32)
y_tensor = torch.tensor(y, dtype=torch.long)

# Print tensor shapes
print("Feature tensor shape:", X_tensor.shape)
print("Label tensor shape:", y_tensor.shape)

# Display first 5 samples
print("\nFirst 5 feature rows:")
print(X_tensor[:5])

print("\nFirst 5 labels:")
print(y_tensor[:5])

Feature tensor shape: torch.Size([150, 4])
Label tensor shape: torch.Size([150])

First 5 feature rows:
tensor([[5.1000, 3.5000, 1.4000, 0.2000],
        [4.9000, 3.0000, 1.4000, 0.2000],
        [4.7000, 3.2000, 1.3000, 0.2000],
        [4.6000, 3.1000, 1.5000, 0.2000],
        [5.0000, 3.6000, 1.4000, 0.2000]])

First 5 labels:
tensor([0, 0, 0, 0, 0])


**Tensor Initialization**

In [ ]:
import torch
# Check for CUDA availability and set the device
device = "cuda" if torch.cuda.is_available() else "cpu"
# Initialize a 2x3 tensor with requires_grad enabled
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device, requires_grad=True)
print(my_tensor)
print("Data type:", my_tensor.dtype)
print("Device:", my_tensor.device)
print("Shape:", my_tensor.shape)
print("Requires Gradient:", my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
Data type: torch.float32
Device: cpu
Shape: torch.Size([2, 3])
Requires Gradient: True


**Basic operation**

In [ ]:
import torch
x=torch.randn(2,2)
y=torch.randn(2,2)
z=x-y
print(z)
z=torch.sub(x,y)

tensor([[-0.3627, -1.4657],
        [-1.6874,  0.7308]])


In [ ]:
# elementwise addition
z = x + y
# torch.add(x,y)

In [ ]:
# in place addition, everythin with a trailing underscore is an inplace operation
# i.e. it will modify the variable
y.add_(x)

tensor([[-1.0724,  1.3044],
        [ 2.2650,  3.3741]])

In [ ]:
# substraction
z = x - y
z = torch.sub(x, y)

In [ ]:
# multiplication
z = x * y
z = torch.mul(x,y)

In [ ]:
# division
z = x / y
z = torch.div(x,y)

**# Slicing**

In [ ]:
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

tensor([[0.2259, 0.5946, 0.1591],
        [0.2912, 0.2907, 0.0752],
        [0.6876, 0.1662, 0.1684],
        [0.3357, 0.5590, 0.2048],
        [0.2628, 0.3595, 0.9076]])
tensor([0.2259, 0.2912, 0.6876, 0.3357, 0.2628])
tensor([0.2912, 0.2907, 0.0752])
tensor(0.2907)


In [ ]:
# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

0.2906551957130432


In [ ]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
# if -1 it pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [ ]:
# Numpy
# Converting a Torch Tensor to a NumPy array and vice versa is very easy
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
# torch to numpy with .numpy()
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [ ]:
# Carful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


# PyTorch Autograd

In [1]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

In [ ]:
# ================================================================== #
#                         Table of Contents                          #
# ================================================================== #

# 1. Basic autograd example 1               (Line 25 to 39)
# 2. Basic autograd example 2               (Line 46 to 83)
# 3. Loading data from numpy                (Line 90 to 97)
# 4. Input pipline                          (Line 104 to 129)
# 5. Input pipline for custom dataset       (Line 136 to 156)
# 6. Pretrained model                       (Line 163 to 176)
# 7. Save and load model                    (Line 183 to 189)


# ================================================================== #
#                     1. Basic autograd example 1                    #
# ================================================================== #

In [2]:
# Create tensors.
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2., requires_grad=True)
b = torch.tensor(3., requires_grad=True)

In [3]:
# Build a computational graph.
y = w * x + b    # y = 2 * x + 3

# Compute gradients.
y.backward()

# Print out the gradients.
print(x.grad)    # x.grad = 2
print(w.grad)    # w.grad = 1
print(b.grad)    # b.grad = 1

tensor(2.)
tensor(1.)
tensor(1.)


In [ ]:
# ================================================================== #
#                    2. Basic autograd example 2                     #
# ================================================================== #

In [4]:
# Create tensors of shape (10, 3) and (10, 2).
x = torch.randn(10, 3)
y = torch.randn(10, 2)

In [5]:
# Build a fully connected layer.
linear = nn.Linear(3, 2)
print ('w: ', linear.weight)
print ('b: ', linear.bias)


w:  Parameter containing:
tensor([[-0.2039, -0.5652, -0.4599],
        [-0.1255, -0.2062,  0.0323]], requires_grad=True)
b:  Parameter containing:
tensor([-0.1125,  0.2044], requires_grad=True)


In [6]:
# Build loss function and optimizer.
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

In [7]:
# Forward pass.
pred = linear(x)

# Compute loss.
loss = criterion(pred, y)
print('loss: ', loss.item())


loss:  2.274979829788208


In [8]:
# Backward pass.
loss.backward()

# Print out the gradients.
print ('dL/dw: ', linear.weight.grad)
print ('dL/db: ', linear.bias.grad)

dL/dw:  tensor([[-0.4192, -1.2478, -1.2139],
        [-1.0104,  0.2345, -0.1887]])
dL/db:  tensor([-0.5040,  0.7137])


In [9]:
# 1-step gradient descent.
optimizer.step()

# You can also perform gradient descent at the low level.
# linear.weight.data.sub_(0.01 * linear.weight.grad.data)
# linear.bias.data.sub_(0.01 * linear.bias.grad.data)

# Print out the loss after 1-step gradient descent.
pred = linear(x)
loss = criterion(pred, y)
print('loss after 1 step optimization: ', loss.item())


loss after 1 step optimization:  2.2247581481933594



**3. Loading data from numpy**                  


In [10]:
# Create a numpy array.
x = np.array([[1, 2], [3, 4]])

# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)

# Convert the torch tensor to a numpy array.
z = y.numpy()

**4. Input pipeline**

In [12]:
# Download and construct CIFAR-10 dataset.
train_dataset = torchvision.datasets.CIFAR10(root='../../data/',
                                             train=True,
                                             transform=transforms.ToTensor(),
                                             download=True)

# Fetch one data pair (read data from disk).
image, label = train_dataset[0]
print (image.size())
print (label)

# Data loader (this provides queues and threads in a very simple way).
train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                           batch_size=64,
                                           shuffle=True)

# When iteration starts, queue and thread start to load data from files.
data_iter = iter(train_loader)

# Mini-batch images and labels.
images, labels = next(data_iter)

# Actual usage of the data loader is as below.
for images, labels in train_loader:
    # Training code should be written here.
    pass

torch.Size([3, 32, 32])
6


**5. Input pipeline for custom dataset**

In [14]:
# You should build your custom dataset as below.
class CustomDataset(torch.utils.data.Dataset):
    def __init__(self):
        # TODO
        # 1. Initialize file paths or a list of file names.
        # For demonstration, let's assume a dataset size of 100 for now.
        self.data_len = 100
        pass
    def __getitem__(self, index):
        # TODO
        # 1. Read one data from file (e.g. using numpy.fromfile, PIL.Image.open).
        # 2. Preprocess the data (e.g. torchvision.Transform).
        # 3. Return a data pair (e.g. image and label).
        # This is a placeholder; you would return actual data here.
        return torch.randn(3, 32, 32), torch.tensor(index % 10)
    def __len__(self):
        # You should change 0 to the total size of your dataset.
        # For now, it returns a placeholder size to avoid the ValueError.
        return self.data_len

# You can then use the prebuilt data loader.
custom_dataset = CustomDataset()
train_loader = torch.utils.data.DataLoader(dataset=custom_dataset,
                                           batch_size=64,
                                           shuffle=True)

**6. Pretrained model**

In [15]:
# Download and load the pretrained ResNet-18.
resnet = torchvision.models.resnet18(pretrained=True)

# If you want to finetune only the top layer of the model, set as below.
for param in resnet.parameters():
    param.requires_grad = False

# Replace the top layer for finetuning.
resnet.fc = nn.Linear(resnet.fc.in_features, 100)  # 100 is an example.

# Forward pass.
images = torch.randn(64, 3, 224, 224)
outputs = resnet(images)
print (outputs.size())     # (64, 100)

/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)


Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth


100%|██████████| 44.7M/44.7M [00:00<00:00, 106MB/s]


torch.Size([64, 100])


**7. Save and load the model**

In [17]:
# ================================================================== #
#                      7. Save and load the model                    #
# ================================================================== #

# Save and load the entire model.
torch.save(resnet, 'model.ckpt')
model = torch.load('model.ckpt', weights_only=False)

# Save and load only the model parameters (recommended).
torch.save(resnet.state_dict(), 'params.ckpt')
resnet.load_state_dict(torch.load('params.ckpt'))

<All keys matched successfully>