<a href="https://colab.research.google.com/github/dr-mushtaq/Deep-Learning/blob/master/Deep_Learning_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#<p style="font-family:JetBrains Mono; font-weight:normal; letter-spacing: 1px; color:#207d06; font-size:100%; text-align:left;padding: 0px; border-bottom: 3px solid #207d06;">**📚Libray and Tools**</p>



1.   [torch.tensor]()-creates a 1D tensor.
2.   [marks.shape]()-shows the dimensions of the tensor.



#<p style="font-family:JetBrains Mono; font-weight:normal; letter-spacing: 1px; color:#207d06; font-size:100%; text-align:left;padding: 0px; border-bottom: 3px solid #207d06;">**📚Chapter: 1-The Fundamentals of PyTorch (Beginner)**</p>

**1D Vector in PyTorch**

In [1]:
import torch
marks = torch.tensor([78, 85, 90, 88, 92])
print(marks)
print(marks.shape)

tensor([78, 85, 90, 88, 92])
torch.Size([5])


**2D Matrix in PyTorch**

In [2]:
import torch
student_marks = torch.tensor([
    [78, 85, 90],
    [88, 92, 80],
    [75, 79, 95]
])
print(student_marks)
print(student_marks.shape)

tensor([[78, 85, 90],
        [88, 92, 80],
        [75, 79, 95]])
torch.Size([3, 3])


**3D Tensor Example in PyTorch**

In [3]:
import torch
tensor_3d = torch.tensor([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])
print(tensor_3d)
print(tensor_3d.shape)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])


**Converting Dataset to PyTorch Tensors**

In [4]:
# Import required libraries
import torch
from sklearn.datasets import load_iris

# Load the built-in Iris dataset
iris = load_iris()

# Features (flower measurements)
X = iris.data

# Labels (flower categories)
y = iris.target

# Convert NumPy arrays to PyTorch tensors
X_tensor = torch.tensor(X, dtype=torch.float32)
y_tensor = torch.tensor(y, dtype=torch.long)

# Print tensor shapes
print("Feature tensor shape:", X_tensor.shape)
print("Label tensor shape:", y_tensor.shape)

# Display first 5 samples
print("\nFirst 5 feature rows:")
print(X_tensor[:5])

print("\nFirst 5 labels:")
print(y_tensor[:5])

Feature tensor shape: torch.Size([150, 4])
Label tensor shape: torch.Size([150])

First 5 feature rows:
tensor([[5.1000, 3.5000, 1.4000, 0.2000],
        [4.9000, 3.0000, 1.4000, 0.2000],
        [4.7000, 3.2000, 1.3000, 0.2000],
        [4.6000, 3.1000, 1.5000, 0.2000],
        [5.0000, 3.6000, 1.4000, 0.2000]])

First 5 labels:
tensor([0, 0, 0, 0, 0])
