<a href="https://colab.research.google.com/github/dr-mushtaq/Deep-Learning/blob/master/Deep_Learning_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#<p style="font-family:JetBrains Mono; font-weight:normal; letter-spacing: 1px; color:#207d06; font-size:100%; text-align:left;padding: 0px; border-bottom: 3px solid #207d06;">**📚Libray and Tools**</p>



1.   [torch.tensor]()-creates a 1D tensor.
2.   [marks.shape]()-shows the dimensions of the tensor.



#<p style="font-family:JetBrains Mono; font-weight:normal; letter-spacing: 1px; color:#207d06; font-size:100%; text-align:left;padding: 0px; border-bottom: 3px solid #207d06;">**📚Chapter: 1-The Fundamentals of PyTorch (Beginner)**</p>

**1D Vector in PyTorch**

In [ ]:
import torch
marks = torch.tensor([78, 85, 90, 88, 92])
print(marks)
print(marks.shape)

tensor([78, 85, 90, 88, 92])
torch.Size([5])


**2D Matrix in PyTorch**

In [ ]:
import torch
student_marks = torch.tensor([
    [78, 85, 90],
    [88, 92, 80],
    [75, 79, 95]
])
print(student_marks)
print(student_marks.shape)

tensor([[78, 85, 90],
        [88, 92, 80],
        [75, 79, 95]])
torch.Size([3, 3])


**3D Tensor Example in PyTorch**

In [ ]:
import torch
tensor_3d = torch.tensor([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])
print(tensor_3d)
print(tensor_3d.shape)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
torch.Size([2, 2, 2])


**Creates a tensor without initializing its values.**

Everything in pytorch is based on Tensor operations.A tensor can have different dimensions so it can be 1d, 2d, or even 3d and higher
scalar, vector, matrix, tensor



*   In PyTorch, torch.empty() creates a tensor without initializing its values.
*   List item



In [3]:
# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(x)

tensor([1.0814e-40])


In [6]:
x = torch.empty(3) # vector, 1D
print(x)

tensor([2.8636e-30, 0.0000e+00, 0.0000e+00])


In [7]:
x = torch.empty(2,3) # matrix, 2D
print(x)

tensor([[1.3573e-27, 0.0000e+00, 7.5525e-12],
        [4.4060e-41, 1.4574e-43, 0.0000e+00]])


In [8]:
x = torch.empty(2,2,3) # tensor, 3 dimensions
#x = torch.empty(2,2,2,3) # tensor, 4 dimensions
print(x)

tensor([[[3.2314e-18, 6.0397e-07, 1.3475e+37],
         [0.0000e+00, 1.1210e-43, 0.0000e+00]],

        [[8.9683e-44, 0.0000e+00, 2.7147e-27],
         [0.0000e+00, 0.0000e+00, 1.5046e-36]]])


**other operation**

In [9]:
# torch.rand(size): random numbers [0, 1]
x = torch.rand(5, 3)
print(x)

tensor([[0.1431, 0.0667, 0.2929],
        [0.3570, 0.1560, 0.8778],
        [0.3742, 0.1811, 0.8992],
        [0.9674, 0.8961, 0.5235],
        [0.7803, 0.7132, 0.9680]])


In [10]:
# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [11]:
# check size
print(x.size())

torch.Size([5, 3])


In [12]:
# check data type
print(x.dtype)

torch.float32


In [13]:
# specify types, float32 default
x = torch.zeros(5, 3, dtype=torch.float16)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)


In [14]:
# construct from data
x = torch.tensor([5.5, 3])
print(x.size())

torch.Size([2])


**Converting Dataset to PyTorch Tensors**

In [ ]:
# Import required libraries
import torch
from sklearn.datasets import load_iris

# Load the built-in Iris dataset
iris = load_iris()

# Features (flower measurements)
X = iris.data

# Labels (flower categories)
y = iris.target

# Convert NumPy arrays to PyTorch tensors
X_tensor = torch.tensor(X, dtype=torch.float32)
y_tensor = torch.tensor(y, dtype=torch.long)

# Print tensor shapes
print("Feature tensor shape:", X_tensor.shape)
print("Label tensor shape:", y_tensor.shape)

# Display first 5 samples
print("\nFirst 5 feature rows:")
print(X_tensor[:5])

print("\nFirst 5 labels:")
print(y_tensor[:5])

Feature tensor shape: torch.Size([150, 4])
Label tensor shape: torch.Size([150])

First 5 feature rows:
tensor([[5.1000, 3.5000, 1.4000, 0.2000],
        [4.9000, 3.0000, 1.4000, 0.2000],
        [4.7000, 3.2000, 1.3000, 0.2000],
        [4.6000, 3.1000, 1.5000, 0.2000],
        [5.0000, 3.6000, 1.4000, 0.2000]])

First 5 labels:
tensor([0, 0, 0, 0, 0])


**Tensor Initialization**

In [2]:
import torch
# Check for CUDA availability and set the device
device = "cuda" if torch.cuda.is_available() else "cpu"
# Initialize a 2x3 tensor with requires_grad enabled
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device, requires_grad=True)
print(my_tensor)
print("Data type:", my_tensor.dtype)
print("Device:", my_tensor.device)
print("Shape:", my_tensor.shape)
print("Requires Gradient:", my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)
Data type: torch.float32
Device: cpu
Shape: torch.Size([2, 3])
Requires Gradient: True


**Basic operation**

In [16]:
import torch
x=torch.randn(2,2)
y=torch.randn(2,2)
z=x-y
print(z)
z=torch.sub(x,y)

tensor([[-0.3627, -1.4657],
        [-1.6874,  0.7308]])


In [17]:
# elementwise addition
z = x + y
# torch.add(x,y)

In [20]:
# in place addition, everythin with a trailing underscore is an inplace operation
# i.e. it will modify the variable
y.add_(x)

tensor([[-1.0724,  1.3044],
        [ 2.2650,  3.3741]])

In [21]:
# substraction
z = x - y
z = torch.sub(x, y)

In [22]:
# multiplication
z = x * y
z = torch.mul(x,y)

In [23]:
# division
z = x / y
z = torch.div(x,y)

**# Slicing**

In [24]:
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

tensor([[0.2259, 0.5946, 0.1591],
        [0.2912, 0.2907, 0.0752],
        [0.6876, 0.1662, 0.1684],
        [0.3357, 0.5590, 0.2048],
        [0.2628, 0.3595, 0.9076]])
tensor([0.2259, 0.2912, 0.6876, 0.3357, 0.2628])
tensor([0.2912, 0.2907, 0.0752])
tensor(0.2907)
